### ISSUE TITLE
DDJ-SX Spoofing no longer seems to work

### ISSUE THREAD

**Issue by shawa** [timkondratiev/RekordJog#11]
Hi there, big fan of this sort of midi hacking! I was wondering what the latest version of RekordBox the project has recently been tested with on macOS - it seems as of 7.0.5 RB no longer picks up the macOS IAC Driver as a controller, even when labelled `PIONEER DDJ-SX`.

Removing this from the `MIDI Studio` causes the script to fail with:

```
OSError: unknown port 'PIONEER DDJ-SX, True'
```

This is with the `CORE` plan, MacOS Sonoma, RB 7.0.5.

More than happy to help out debugging!

**Comment by timkondratev** [comment]
Hi, thank you for your feedback! I tested it with rekordbox 7.0.4 and it worked.

Did it work with earlier versions of RB on your system?

On MacOS you don't need to manually create a device in MIDI studio. It is created automatically in Python.

**Comment by shawa** [comment]
I had a closer read of the code, and also having turned off the IAC driver got it to recognise it, thank you!

I was actually looking to intercept events coming from a FLX4 so that I can use it to control 4 rather than the stock 2 channels.

For posterity, interestingly it seems if Rekordbox starts up whilst both the FLX4 and the (virtual) SX are connected, it connects to the SX. But if it's already started _with_ the FLX4 connected, and _then_ the virtual SX is started, it doesn't recognise it.

Thanks for the help. Happy to close this for the moment so I don't clog up your issue backlog 😄

**Comment by timkondratev** [comment]
Great to hear that! 

I had the same idea of extending a 2 deck controller to 4 decks. We will try to adapt the program for this use case in future versions.

You can write me a direct message on Reddit to further describe the problem and your end goal.
